### ISSUE TITLE
Bug feedback【bug反馈】

### ISSUE THREAD

**Issue by zhs509** [codito/pyqtkeybind#1] opened 2018-04-25 05:51 UTC
First,sorry for my pool english.

Bug feedback:The registered hotkey part is invalid
------------------------------------------------------------------------------------------------
Such as:Ctrl+Q、Shift+Q、Ctrl+Alt+Q、Alt+Q，only the last one Alt+Q to be valid，
While Register:Ctrl+Q、Ctrl+R or Shift+Q、Ctrl+R、Alt+M, all effective。

bug反馈，注册热键部分失效：
例如：Ctrl+Q、Shift+Q、Ctrl+Alt+Q、Alt+Q，只有最后一个Alt+Q有效。而注册Ctrl+Q、Ctrl+R or Shift+Q、Ctrl+R、Alt+M，这些都有效

**Comment by codito** [comment] 2018-04-26 00:16
@zhs509 thank you for reporting this. Can you please share the following?
- OS version
- Python, PyQt5 version
- Is there a sample app I can try?

I modified the [sample/hotkey.py](https://github.com/codito/pyqtkeybind/blob/master/sample/hotkey.py) file in this repo, but couldn't reproduce the issue on Arch Linux with Python 3.6.5 and PyQt5 5.10.

```diff
diff --git a/sample/hotkey.py b/sample/hotkey.py
index 1b9a793..c30c30c 100644
--- a/sample/hotkey.py
+++ b/sample/hotkey.py
@@ -34,7 +34,8 @@ def main():
         print("hello world")
     def exit_app():
         window.close()
-    keybinder.register_hotkey(window.winId(), "Shift+Ctrl+A", callback)
+    # keybinder.register_hotkey(window.winId(), "Shift+Ctrl+A", callback)
+    keybinder.register_hotkey(window.winId(), "Alt+Ctrl+Q", callback)
     keybinder.register_hotkey(window.winId(), "Shift+Ctrl+E", exit_app)
 
     # Install a native event filter to receive events from the OS

```

Is it possible that another application is capturing the hotkeys?

**Comment by zhs509** [comment] 2018-04-26 01:10
thanks a lot。python3.6.5、Pyqt5.10.1、windows 10


# -*- coding: utf-8 -*-
"""
@python: python3.6.5
@Pyqt5: Pyqt5.10.1
@Platform: windows 10
"""

import sys

from PyQt5 import QtWidgets
from PyQt5.QtCore import QAbstractNativeEventFilter, QAbstractEventDispatcher

from pyqtkeybind import keybinder

class WinEventFilter(QAbstractNativeEventFilter):
    def __init__(self, keybinder):
        self.keybinder = keybinder
        super().__init__()

    def nativeEventFilter(self, eventType, message):
        ret = self.keybinder.handler(eventType, message)
        return ret, 0

class Hotkey_capture():
    """
    Capture the hotkey and print hotkey
    """
    def __init__(self,key):
        self.key=key
    def callback(self):
        result = "hello world,Hotkey is {}".format(self.key)
        print(result)

def main():
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()

    keybinder.init()

    for key in [
        "Ctrl+Shift+Q",
        "Alt+Shift+Q",
        "Ctrl+Alt+Q",
        "Ctrl+Q",
        "Shift+Q",
        "Alt+Q",    # if Q is used，only the last one is effective

        "Alt+Esc",    # Ctrl+E is effective
        "Shift+F2",    # Alt+F is effective
    ]:
        # Hotkey_capture capturing the hotkey, hotkey.callback return capturing hotkey
        hotkey = Hotkey_capture(key)
        keybinder.register_hotkey(window.winId(), key, hotkey.callback)

    # Install a native event filter to receive events from the OS
    win_event_filter = WinEventFilter(keybinder)
    event_dispatcher = QAbstractEventDispatcher.instance()
    event_dispatcher.installNativeEventFilter(win_event_filter)

    window.show()
    app.exec_()
    keybinder.unregister_hotkey(window.winId(), 0x0, 0x0)

if __name__ == '__main__':
    main()

**Comment by zhs509** [comment] 2018-04-26 01:11
``# -*- coding: utf-8 -*-
"""
@python: python3.6.5
@Pyqt5: Pyqt5.10.1
@Platform: win10
"""

import sys

from PyQt5 import QtWidgets
from PyQt5.QtCore import QAbstractNativeEventFilter, QAbstractEventDispatcher

from pyqtkeybind import keybinder

class WinEventFilter(QAbstractNativeEventFilter):
    def __init__(self, keybinder):
        self.keybinder = keybinder
        super().__init__()

    def nativeEventFilter(self, eventType, message):
        ret = self.keybinder.handler(eventType, message)
        return ret, 0

class Hotkey_capture():
    """
    Capture the hotkey and print hotkey
    """
    def __init__(self,key):
        self.key=key
    def callback(self):
        result = "hello world,Hotkey is {}".format(self.key)
        print(result)

def main():
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()

    keybinder.init()

    for key in [
        "Ctrl+Shift+Q",
        "Alt+Shift+Q",
        "Ctrl+Alt+Q",
        "Ctrl+Q",
        "Shift+Q",
        "Alt+Q",    #if Q is used，only the last one is effective

        "Alt+Esc", # Ctrl+E is effective
        "Shift+F2",    # Alt+F is effective
    ]:
        # Hotkey_capture capturing the hotkey, hotkey.callback return capturing hotkey
        hotkey = Hotkey_capture(key)
        keybinder.register_hotkey(window.winId(), key, hotkey.callback)

    # Install a native event filter to receive events from the OS
    win_event_filter = WinEventFilter(keybinder)
    event_dispatcher = QAbstractEventDispatcher.instance()
    event_dispatcher.installNativeEventFilter(win_event_filter)

    window.show()
    app.exec_()
    keybinder.unregister_hotkey(window.winId(), 0x0, 0x0)

if __name__ == '__main__':
    main()

**Comment by zhs509** [comment] 2018-04-26 01:21
Thanks a lot。python3.6.5、Pyqt5.10.1、windows 10

```
# -*- coding: utf-8 -*-
"""
@python: python3.6.5
@Pyqt5: Pyqt5.10.1
@Platform: win10
"""

import sys

from PyQt5 import QtWidgets
from PyQt5.QtCore import QAbstractNativeEventFilter, QAbstractEventDispatcher

from pyqtkeybind import keybinder

class WinEventFilter(QAbstractNativeEventFilter):
    def __init__(self, keybinder):
        self.keybinder = keybinder
        super().__init__()

    def nativeEventFilter(self, eventType, message):
        ret = self.keybinder.handler(eventType, message)
        return ret, 0

class Hotkey_capture():
    """
    Capture the hotkey and print hotkey
    """
    def __init__(self,key):
        self.key=key
    def callback(self):
        result = "hello world,Hotkey is {}".format(self.key)
        print(result)

def main():
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()

    keybinder.init()

    for key in [
        "Ctrl+Shift+Q",
        "Alt+Shift+Q",
        "Ctrl+Alt+Q",
        "Ctrl+Q",
        "Shift+Q",
        "Alt+Q",    #if Q is used，only the last one is effective

        "Alt+Esc", # Ctrl+E is effective
        "Shift+F2",    # Alt+F is effective
    ]:
        # Hotkey_capture capturing the hotkey, hotkey.callback return capturing hotkey
        hotkey = Hotkey_capture(key)
        keybinder.register_hotkey(window.winId(), key, hotkey.callback)

    # Install a native event filter to receive events from the OS
    win_event_filter = WinEventFilter(keybinder)
    event_dispatcher = QAbstractEventDispatcher.instance()
    event_dispatcher.installNativeEventFilter(win_event_filter)

    window.show()
    app.exec_()
    keybinder.unregister_hotkey(window.winId(), 0x0, 0x0)

if __name__ == '__main__':
    main()
```

**Comment by codito** [comment] 2018-04-26 01:48
Thanks! I am able to reproduce the issue, will investigate further.

**Comment by codito** [comment] 2018-04-26 02:22
Fixed with 48bfb3f4dfc1014a5abad234b8f17092796eee9c. Released v0.0.3 to pypi. Please try `pip install --upgrade pyqtkeybind`.

Note that the syntax of `unregister_hotkey` is changed. Example https://github.com/codito/pyqtkeybind/blob/master/sample/hotkey.py#L47-L48

**Comment by zhs509** [comment] 2018-04-26 03:26
> 

修复了48bfb3f。发布v0.0.3到pypi。请尝试pip install --upgrade pyqtkeybind。请注意，语法unregister_hotkey已更改。示例https://github.com/codito/pyqtkeybind/blob/master/sample/hotkey.py#L47-L48
> 
thanks a lot. All  registered hotkeys are ok.

**Comment by zhs509** [comment] 2018-04-26 03:27
Thanks a lot. All registered hotkeys are ok.

**Comment by codito** [comment] 2018-04-26 03:38
Thanks for confirmation!

**Closed as completed by codito** 2018-04-26 03:38 UTC
